package org.ncu.hirewheels.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id", nullable = false, precision = 10)
    private Long userId;

    @Column(name = "first_name", nullable = false, length = 50)

    private String firstName;

    @Column(name = "last_name", length = 50)
    private String lastName;

    @Column(name = "password", nullable = false, length = 50)

    private String password;

    @Column(name = "email", nullable = false, length = 50, unique = true)

    private String email;

    @Column(name = "mobile_no", nullable = false, length = 10, unique = true)

    private String mobileNumber;

    @Column(name = "wallet_money", columnDefinition = "NUMERIC(10,2) DEFAULT 10000.00")
    private Double walletMoney;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "role_id")
    private Role role;

    @OneToMany(mappedBy = "user")
    private List<Booking> bookings;

    // toString() method is automatically generated by Lombok's @Data annotation
}
